### ISSUE TITLE
Security: GitHub Action potential script injection.

### ISSUE THREAD

**Issue by kaladay** [TAMULib/SAGE#562]
Using GitHub variable substition inside of inline scripts (the `run:` sections) can allow for injections.
Wrapping variables inside environment variables resolves this potential exploit.

see: https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

### Example Problem
```yaml
    - name: Construct full image tag
      run: echo "FULL_IMAGE_TAG=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/sage:${{ env.VERSION }}-${{ env.SHORT_SHA }}" >> $GITHUB_ENV
```

### Example Proposed Solution
```yaml
    - name: Construct full image tag
      env:
        HARBOR_URL_SECRET: ${{ secrets.HARBOR_URL }}
        HARBOR_PROJECT: ${{ secrets.HARBOR_PROJECT }}
      run: echo "FULL_IMAGE_TAG=${HARBOR_URL_SECRET}/${HARBOR_PROJECT}/sage:${VERSION}-${SHORT_SHA}" >> $GITHUB_ENV
```

### Additional Notes
The GitHub environment variables that are created in `$GITHUB_ENV` can simply directly be accessed via the environment variable name, such as `${MY_ENV_VAR}`, rather than using the `${{ env. }}` syntax, such as `${{ env.MY_ENV_VAR }}`.

see: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable

#### Example from GitHub's Documentation
```
steps:
  - name: Set the value
    id: step_one
    run: |
      echo "action_state=yellow" >> "$GITHUB_ENV"
  - name: Use the value
    id: step_two
    run: |
      printf '%s\n' "$action_state" # This will output 'yellow'
```
